# generated by zon2nix (https://github.com/nix-community/zon2nix)

{
  linkFarm,
  fetchzip,
  fetchgit,
}:

linkFarm "zig-packages" [
  {
    name = "N-V-__8AAAZ8QgBoM0e_aCVlmr4bXY3hGnNSWSWNhluMsCs5";
    path = fetchzip {
      url = "https://codeload.github.com/ashvardanian/StringZilla/tar.gz/refs/tags/v4.5.1";
      hash = "sha256-0T8hQ+P6gZnIX52jkRcpF1Ofxy45+B7K/feEQr5Phf0=";
    };
  }
  {
    name = "httpz-0.0.0-PNVzrEnoCADpf8B42EMPO2WmIlvsQJ0dJ8oCWjnl6CIX";
    path = fetchzip {
      url = "https://codeload.github.com/karlseguin/http.zig/tar.gz/86a44b63bda353338f2dbddc35eeb260f0f5c299";
      hash = "sha256-QjQa+J+4W/Z7Bu5YcZP5T2iZ7n38rEH5mjH7fGL6Tkc=";
    };
  }
  {
    name = "metrics-0.0.0-W7G4eIegAQD4XxA9Co7Atbw59u_2zvxYf406AZuoAHPM";
    path = fetchzip {
      url = "https://codeload.github.com/karlseguin/metrics.zig/tar.gz/6de29b83a750a06c438d268543e0e3c3c1b309da";
      hash = "sha256-F0tnpGmcPtNIff+i9z9ZVWttLvAKQNXQzVAKnsSFV+o=";
    };
  }
  {
    name = "noscrypt-0.1.14-q33-Y3suyADLggvQIxeDkW7bCwZA4VuR2zAnm9M2Sbva";
    path = fetchzip {
      url = "https://codeload.github.com/privkeyio/noscrypt/tar.gz/01f2ed5801198da139fd9856dcc475a80121acf5";
      hash = "sha256-+pEzkUeXGFjfMnNcezbxknnsVhgu97Vf3asNo3lgfIM=";
    };
  }
  {
    name = "nostr-0.3.6-JY6OcLPKDwAP8UJz5qRAVc4LKg3AB2zE7Eok-gky9o4d";
    path = fetchzip {
      url = "https://codeload.github.com/privkeyio/libnostr-z/tar.gz/refs/tags/v0.3.6";
      hash = "sha256-uCt2U8KRoF0W2oK8KzB8rEt32lbD+pMaVwVL/9XaBYw=";
    };
  }
  {
    name = "websocket-0.1.0-ZPISdangBAAgWPap_MVU6Nk4rj3GT3xuJuF0IIv8HN6G";
    path = fetchzip {
      url = "https://codeload.github.com/karlseguin/websocket.zig/tar.gz/99df0d3533a41cbcd5ff59b9af68bbfe6169cc62";
      hash = "sha256-Ol+yLbGAfgb+tWzfK5LTC6Ti7m36U3y8J//JYoULAvw=";
    };
  }
]
