# Offline package cache for the Nix build: one entry per Zig package that
# `zig build` resolves, keyed by the exact hash from a build.zig.zon.
#
# MAINTAINED BY HAND. Originally generated by zon2nix
# (https://github.com/nix-community/zon2nix), but zon2nix now fails on our
# manifest with `error: parseError` because it cannot express the vendored path
# dependency on vendor/httpz. Do not expect to regenerate this file; edit it.
#
# The entries must cover the union of build.zig.zon AND vendor/httpz/build.zig.zon
# (the vendored copy pulls in metrics and websocket of its own). A `name` here has
# to match the dependency's `.hash` character for character, or zig reports
# "package not found" against this store path. httpz itself has no entry: it is a
# path dependency, so it is part of the source tree rather than the cache.
#
# `extension = "tar.gz"` is added to each fetchzip: the codeload `/tar.gz/<rev>` URLs have a bare
# rev basename with no archive suffix, so without it fetchzip's unpackFile fails with "do not know
# how to unpack source archive" on any cache miss. The extension names the intermediate download
# `download.tar.gz` so unpackFile recognises it.
#
# Drift guards, and their limits: the `nix package build` job in
# .github/workflows/ci.yml builds this for real, which catches an entry that is
# MISSING, and scripts/verify-nix-deps.sh catches the same case cheaply plus a
# package.nix version that has drifted from build.zig.zon. Neither catches an
# entry that is EXTRA -- zig ignores what it does not resolve -- which is how the
# obsolete httpz entry survived here for two releases. That needs the transitive
# closure; see the note in scripts/verify-nix-deps.sh for the upgrade path.

{
  linkFarm,
  fetchzip,
  fetchgit,
}:

linkFarm "zig-packages" [
  {
    name = "N-V-__8AAAZ8QgBoM0e_aCVlmr4bXY3hGnNSWSWNhluMsCs5";
    path = fetchzip {
      url = "https://codeload.github.com/ashvardanian/StringZilla/tar.gz/refs/tags/v4.5.1";
      hash = "sha256-0T8hQ+P6gZnIX52jkRcpF1Ofxy45+B7K/feEQr5Phf0=";
      extension = "tar.gz";
    };
  }
  {
    name = "metrics-0.0.0-W7G4eIegAQD4XxA9Co7Atbw59u_2zvxYf406AZuoAHPM";
    path = fetchzip {
      url = "https://codeload.github.com/karlseguin/metrics.zig/tar.gz/6de29b83a750a06c438d268543e0e3c3c1b309da";
      hash = "sha256-F0tnpGmcPtNIff+i9z9ZVWttLvAKQNXQzVAKnsSFV+o=";
      extension = "tar.gz";
    };
  }
  {
    name = "noscrypt-0.1.14-q33-Y3suyADLggvQIxeDkW7bCwZA4VuR2zAnm9M2Sbva";
    path = fetchzip {
      url = "https://codeload.github.com/privkeyio/noscrypt/tar.gz/01f2ed5801198da139fd9856dcc475a80121acf5";
      hash = "sha256-+pEzkUeXGFjfMnNcezbxknnsVhgu97Vf3asNo3lgfIM=";
      extension = "tar.gz";
    };
  }
  {
    name = "nostr-0.3.7-JY6OcKvaDwCO3EVbmfv4WRreC-IPbZHtrBAAyMHNYmWH";
    path = fetchzip {
      url = "https://codeload.github.com/privkeyio/libnostr-z/tar.gz/refs/tags/v0.3.7";
      hash = "sha256-7+p+6Jt7vKU3XZvIDO2oqtWqKGCky+/h1vmTevK4XVM=";
      extension = "tar.gz";
    };
  }
  {
    name = "websocket-0.1.0-ZPISdUoQBQC7zw1uSwbOEYdxZiTxNN4nf9RlWBsN0_Nd";
    path = fetchzip {
      url = "https://codeload.github.com/karlseguin/websocket.zig/tar.gz/b70e733bc0d0ba0a98ff5fe5ef64d3017c85f369";
      hash = "sha256-R+N4XZfObDDTKD4b+cBgEyQ8yA1IetWxD3g9+wNrFlE=";
      extension = "tar.gz";
    };
  }
]
