# Offline package cache for the Nix build: one entry per Zig package that
# `zig build` resolves, keyed by the exact hash from a build.zig.zon.
#
# MAINTAINED BY HAND. Originally generated by zon2nix
# (https://github.com/nix-community/zon2nix), but zon2nix now fails on our
# manifest with `error: parseError` because it cannot express the vendored path
# dependency on vendor/httpz. Do not expect to regenerate this file; edit it.
#
# The entries must cover the union of build.zig.zon AND vendor/httpz/build.zig.zon
# (the vendored copy pulls in metrics and websocket of its own). A `name` here has
# to match the dependency's `.hash` character for character, or zig reports
# "package not found" against this store path. httpz itself has no entry: it is a
# path dependency, so it is part of the source tree rather than the cache.
#
# `extension = "tar.gz"` is added to each fetchzip: the codeload `/tar.gz/<rev>` URLs have a bare
# rev basename with no archive suffix, so without it fetchzip's unpackFile fails with "do not know
# how to unpack source archive" on any cache miss. The extension names the intermediate download
# `download.tar.gz` so unpackFile recognises it.
#
# Drift guards, and their limits: the `nix package build` job in
# .github/workflows/ci.yml builds this for real, which catches an entry that is
# MISSING, and scripts/verify-nix-deps.sh catches the same case cheaply plus a
# package.nix version that has drifted from build.zig.zon. Neither catches an
# entry that is EXTRA -- zig ignores what it does not resolve -- which is how the
# obsolete httpz entry survived here for two releases. That needs the transitive
# closure; see the note in scripts/verify-nix-deps.sh for the upgrade path.

{
  linkFarm,
  fetchzip,
  fetchgit,
}:

linkFarm "zig-packages" [
  {
    name = "N-V-__8AAAZ8QgBoM0e_aCVlmr4bXY3hGnNSWSWNhluMsCs5";
    path = fetchzip {
      url = "https://codeload.github.com/ashvardanian/StringZilla/tar.gz/refs/tags/v4.5.1";
      hash = "sha256-0T8hQ+P6gZnIX52jkRcpF1Ofxy45+B7K/feEQr5Phf0=";
      extension = "tar.gz";
    };
  }
  {
    name = "metrics-0.0.0-W7G4eGWhAQC-C6tpIW3uxJp-vl6rLyfJvoqJRLzF1SuS";
    path = fetchzip {
      url = "https://codeload.github.com/karlseguin/metrics.zig/tar.gz/ac167295b6a8fd84ca7af852c1032e6b246101f0";
      hash = "sha256-8WmT4KIILQzRWYcDZa1uxXnrLWfqQnOxFy1T6FXAC5M=";
      extension = "tar.gz";
    };
  }
  {
    name = "noscrypt-0.1.14-q33-Y3suyADLggvQIxeDkW7bCwZA4VuR2zAnm9M2Sbva";
    path = fetchzip {
      url = "https://codeload.github.com/privkeyio/noscrypt/tar.gz/01f2ed5801198da139fd9856dcc475a80121acf5";
      hash = "sha256-+pEzkUeXGFjfMnNcezbxknnsVhgu97Vf3asNo3lgfIM=";
      extension = "tar.gz";
    };
  }
  {
    name = "nostr-0.5.0-JY6OcKMgEABIisCx3kmE4ybZbmnO5PyWyodAGjukxEJs";
    path = fetchzip {
      url = "https://codeload.github.com/privkeyio/libnostr-z/tar.gz/5accad27a7ad71d503cd3c8152ea9540d2c23cda";
      hash = "sha256-IUlaSqrRE6TRK4v6oDw251y6Jm0pSjlmPW7IzQ48wd8=";
      extension = "tar.gz";
    };
  }
  {
    name = "websocket-0.1.0-ZPISdbERBQCnk2-UDVSJlOss6POs_aAJR2nrccYJ1wZm";
    path = fetchzip {
      url = "https://codeload.github.com/karlseguin/websocket.zig/tar.gz/f2b3bad6875595e8dd42c726e8e914885a8b0ba0";
      hash = "sha256-5wd+XSmD6fnO0keWsROtvvkq8oI3WMR3OjRN5HmfI2A=";
      extension = "tar.gz";
    };
  }
]
